// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLczFTm2YURvMg_PHXSBIOTNK5u5ZMuSs',
    appId: '1:713551224124:web:42b6e2d7e1706523631239',
    messagingSenderId: '713551224124',
    projectId: 'movieverse-d3145',
    authDomain: 'movieverse-d3145.firebaseapp.com',
    storageBucket: 'movieverse-d3145.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ5SKJTtq4ZQj8RAz56PABkwzYdyJbKdc',
    appId: '1:713551224124:android:eee05b82e3be1016631239',
    messagingSenderId: '713551224124',
    projectId: 'movieverse-d3145',
    storageBucket: 'movieverse-d3145.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMgUFMv6HqqFxP3s7u6EC5usYpgfY7lZE',
    appId: '1:713551224124:ios:c44297826fa97b73631239',
    messagingSenderId: '713551224124',
    projectId: 'movieverse-d3145',
    storageBucket: 'movieverse-d3145.firebasestorage.app',
    iosBundleId: 'com.example.movieverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMgUFMv6HqqFxP3s7u6EC5usYpgfY7lZE',
    appId: '1:713551224124:ios:c44297826fa97b73631239',
    messagingSenderId: '713551224124',
    projectId: 'movieverse-d3145',
    storageBucket: 'movieverse-d3145.firebasestorage.app',
    iosBundleId: 'com.example.movieverse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLczFTm2YURvMg_PHXSBIOTNK5u5ZMuSs',
    appId: '1:713551224124:web:550c60d77a574291631239',
    messagingSenderId: '713551224124',
    projectId: 'movieverse-d3145',
    authDomain: 'movieverse-d3145.firebaseapp.com',
    storageBucket: 'movieverse-d3145.firebasestorage.app',
  );
}
